spring:
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 1000
      generate-statistics: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/coffeeshop"
    username: barista_owner
    password: 271985
  properties:
    hibernate:
      default_schema: barista_owner
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8081